model:
  src_vocab_size: 220                                # Vocabulary size for source data. A reasonable amount is base + 7 for the special tokens.
  tgt_vocab_size: 220                                # Vocabulary size for target data. A reasonable amount is base + 7 for the special tokens.
  d_model: 128                                     # Dimension of the model embedding
  num_heads: 4                                     # Number of attention heads
  d_ff: 256                                        # Dimension of the feedforward network
  num_encoder_layers: 1
  num_decoder_layers: 1
  max_len: 128                                     # Maximum sequence length. A reasonable value is the length of the longest input sequence in your dataset.
  dropout: 0                                       # Dropout rate
  architecture: 'encoder_decoder'                  # encoder_decoder, encoder_only, decoder_only
  is_sinusoidal: false                             # Whether to use sinusoidal positional encoding

training:
  experiment_name: 'ap2Weierstrass'
  batch_size: 32
  num_epochs: 150     
  learning_rate: 0.0001
  weight_decay: 0.0                                 # Weight decay for optimizer
  cache_dir: 'cache'                                # Directory to store training logs and models
  seed: 42                                          # Random seed for reproducibility
  eval_size: 10000                                  # maximum number of evaluation samples as generation is slow

data:
  base: 100                                         # base to encode integers
  eval_size: 10000                                  # maximum number of evaluation samples
  data_path: 'data/data.parquet'                    # path to save/load the dataset
  seed: 42                                          # Random seed for reproducibility

device:
  use_cuda: true